### ISSUE TITLE
Why is .bash_enter and .bash_leave deprecated?

### ISSUE THREAD

**Issue by jedvardsson** [cxreg/smartcd#46]
Hi,

I've just installed smartcd and by the first look it looks like an excellent work. I have one question though: what is the reason for deprecating .bash_enter and .bash_leave? 

I agree that it is nice to have out-of-directory control of smartcd, but in-directory is nice too. In my case I would like to commit the .bash_enter to version control so other project members can benefit from getting PATH settings automatically.

**Comment by cxreg** [comment]
The reason is just what you cited.  If you think about the malicious possibilities for this, it's too easy to have code executed without wanting or expecting it.  This could happen as part of distributed software either on purpose or by accident, and alsother could be left by other users on a shared system (if you cd to my home directory you nuke your own)

It may be reasonable to have a mode where it prompts you about an unexpected script, shows you the contents, and remembers a checksum for future trust.   I'll think about this a bit.

**Comment by jedvardsson** [comment]
I understand. Your suggest solution with checksum would be great though. I'll see if I can find some time to look into it.

**Comment by jedvardsson** [comment]
I submitted a pull request that implements the checksum trust feature for 'local' .bash_enter/.bash_leave. 
https://github.com/cxreg/smartcd/pull/47
